Traceback (most recent call last):
  File "/Users/gollum/anaconda3/envs/scipy-dv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/gollum/anaconda3/envs/scipy-dv/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/gollum/anaconda3/envs/scipy-dv/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/gollum/anaconda3/envs/scipy-dv/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/gollum/anaconda3/envs/scipy-dv/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/gollum/anaconda3/envs/scipy-dv/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/gollum/anaconda3/envs/scipy-dv/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/gollum/anaconda3/envs/scipy-dv/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Standard python numerical analysis imports:
import numpy as np
import torch

# https://github.com/numpy/numpy/pull/18585/
# import numpy.array_api as xp 

import math
import scipy
from scipy import signal
from scipy.interpolate import interp1d  # Not compatible yet
from scipy.signal import butter, filtfilt  # Not compatible yet

# !pip install h5py
import h5py
import json

# plotting items
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab

# -- Set some parameters that control how plots are displayed
plt.rcParams['figure.figsize'] = [5, 3]
plt.rcParams['lines.linewidth'] = .75

# LIGO-specific readligo.py 
# Download from https://www.gw-openscience.org/static/sample_code/readligo.py
# Note: This has been edited for the PyTorch demo with array-api available at,
#       https://github.com/AnirudhDagar/array-api-demo/blob/master/readligo.py
import readligo as rl
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/var/folders/zk/wctnbpzn05bgl3h0h8mn0q140000gn/T/ipykernel_60761/2752603362.py[0m in [0;36m<module>[0;34m[0m
[1;32m      8[0m [0;32mimport[0m [0mmath[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0;32mimport[0m [0mscipy[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m [0;32mfrom[0m [0mscipy[0m [0;32mimport[0m [0msignal[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m [0;32mfrom[0m [0mscipy[0m[0;34m.[0m[0minterpolate[0m [0;32mimport[0m [0minterp1d[0m  [0;31m# Not compatible yet[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0;32mfrom[0m [0mscipy[0m[0;34m.[0m[0msignal[0m [0;32mimport[0m [0mbutter[0m[0;34m,[0m [0mfiltfilt[0m  [0;31m# Not compatible yet[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Desktop/Work/scipy/scipy/signal/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m    295[0m [0;32mfrom[0m [0;34m.[0m[0m_upfirdn[0m [0;32mimport[0m [0mupfirdn[0m[0;34m[0m[0;34m[0m[0m
[1;32m    296[0m [0;34m[0m[0m
[0;32m--> 297[0;31m from ._spline import (  # noqa: F401
[0m[1;32m    298[0m  [0mcspline2d[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    299[0m  [0mqspline2d[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'scipy.signal._spline'
ModuleNotFoundError: No module named 'scipy.signal._spline'

